QUICK_DRAWING_NAMES = [
    "aircraft carrier",
    "airplane",
    "alarm clock",
    "ambulance",
    "angel",
    "animal migration",
    "ant",
    "anvil",
    "apple",
    "arm",
    "asparagus",
    "axe",
    "backpack",
    "banana",
    "bandage",
    "barn",
    "baseball bat",
    "baseball",
    "basket",
    "basketball",
    "bat",
    "bathtub",
    "beach",
    "bear",
    "beard",
    "bed",
    "bee",
    "belt",
    "bench",
    "bicycle",
    "binoculars",
    "bird",
    "birthday cake",
    "blackberry",
    "blueberry",
    "book",
    "boomerang",
    "bottlecap",
    "bowtie",
    "bracelet",
    "brain",
    "bread",
    "bridge",
    "broccoli",
    "broom",
    "bucket",
    "bulldozer",
    "bus",
    "bush",
    "butterfly",
    "cactus",
    "cake",
    "calculator",
    "calendar",
    "camel",
    "camera",
    "camouflage",
    "campfire",
    "candle",
    "cannon",
    "canoe",
    "car",
    "carrot",
    "castle",
    "cat",
    "ceiling fan",
    "cell phone",
    "cello",
    "chair",
    "chandelier",
    "church",
    "circle",
    "clarinet",
    "clock",
    "cloud",
    "coffee cup",
    "compass",
    "computer",
    "cookie",
    "cooler",
    "couch",
    "cow",
    "crab",
    "crayon",
    "crocodile",
    "crown",
    "cruise ship",
    "cup",
    "diamond",
    "dishwasher",
    "diving board",
    "dog",
    "dolphin",
    "donut",
    "door",
    "dragon",
    "dresser",
    "drill",
    "drums",
    "duck",
    "dumbbell",
    "ear",
    "elbow",
    "elephant",
    "envelope",
    "eraser",
    "eye",
    "eyeglasses",
    "face",
    "fan",
    "feather",
    "fence",
    "finger",
    "fire hydrant",
    "fireplace",
    "firetruck",
    "fish",
    "flamingo",
    "flashlight",
    "flip flops",
    "floor lamp",
    "flower",
    "flying saucer",
    "foot",
    "fork",
    "frog",
    "frying pan",
    "garden hose",
    "garden",
    "giraffe",
    "goatee",
    "golf club",
    "grapes",
    "grass",
    "guitar",
    "hamburger",
    "hammer",
    "hand",
    "harp",
    "hat",
    "headphones",
    "hedgehog",
    "helicopter",
    "helmet",
    "hexagon",
    "hockey puck",
    "hockey stick",
    "horse",
    "hospital",
    "hot air balloon",
    "hot dog",
    "hot tub",
    "hourglass",
    "house plant",
    "house",
    "hurricane",
    "ice cream",
    "jacket",
    "jail",
    "kangaroo",
    "key",
    "keyboard",
    "knee",
    "knife",
    "ladder",
    "lantern",
    "laptop",
    "leaf",
    "leg",
    "light bulb",
    "lighter",
    "lighthouse",
    "lightning",
    "line",
    "lion",
    "lipstick",
    "lobster",
    "lollipop",
    "mailbox",
    "map",
    "marker",
    "matches",
    "megaphone",
    "mermaid",
    "microphone",
    "microwave",
    "monkey",
    "moon",
    "mosquito",
    "motorbike",
    "mountain",
    "mouse",
    "moustache",
    "mouth",
    "mug",
    "mushroom",
    "nail",
    "necklace",
    "nose",
    "ocean",
    "octagon",
    "octopus",
    "onion",
    "oven",
    "owl",
    "paint can",
    "paintbrush",
    "palm tree",
    "panda",
    "pants",
    "paper clip",
    "parachute",
    "parrot",
    "passport",
    "peanut",
    "pear",
    "peas",
    "pencil",
    "penguin",
    "piano",
    "pickup truck",
    "picture frame",
    "pig",
    "pillow",
    "pineapple",
    "pizza",
    "pliers",
    "police car",
    "pond",
    "pool",
    "popsicle",
    "postcard",
    "potato",
    "power outlet",
    "purse",
    "rabbit",
    "raccoon",
    "radio",
    "rain",
    "rainbow",
    "rake",
    "remote control",
    "rhinoceros",
    "rifle",
    "river",
    "roller coaster",
    "rollerskates",
    "sailboat",
    "sandwich",
    "saw",
    "saxophone",
    "school bus",
    "scissors",
    "scorpion",
    "screwdriver",
    "sea turtle",
    "see saw",
    "shark",
    "sheep",
    "shoe",
    "shorts",
    "shovel",
    "sink",
    "skateboard",
    "skull",
    "skyscraper",
    "sleeping bag",
    "smiley face",
    "snail",
    "snake",
    "snorkel",
    "snowflake",
    "snowman",
    "soccer ball",
    "sock",
    "speedboat",
    "spider",
    "spoon",
    "spreadsheet",
    "square",
    "squiggle",
    "squirrel",
    "stairs",
    "star",
    "steak",
    "stereo",
    "stethoscope",
    "stitches",
    "stop sign",
    "stove",
    "strawberry",
    "streetlight",
    "string bean",
    "submarine",
    "suitcase",
    "sun",
    "swan",
    "sweater",
    "swing set",
    "sword",
    "syringe",
    "t-shirt",
    "table",
    "teapot",
    "teddy-bear",
    "telephone",
    "television",
    "tennis racquet",
    "tent",
    "The Eiffel Tower",
    "The Great Wall of China",
    "The Mona Lisa",
    "tiger",
    "toaster",
    "toe",
    "toilet",
    "tooth",
    "toothbrush",
    "toothpaste",
    "tornado",
    "tractor",
    "traffic light",
    "train",
    "tree",
    "triangle",
    "trombone",
    "truck",
    "trumpet",
    "umbrella",
    "underwear",
    "van",
    "vase",
    "violin",
    "washing machine",
    "watermelon",
    "waterslide",
    "whale",
    "wheel",
    "windmill",
    "wine bottle",
    "wine glass",
    "wristwatch",
    "yoga",
    "zebra",
    "zigzag",
    ]

QUICK_DRAWING_FILES = {
    "aircraft carrier": "aircraft carrier.bin",
    "airplane": "airplane.bin",
    "alarm clock": "alarm clock.bin",
    "ambulance": "ambulance.bin",
    "angel": "angel.bin",
    "animal migration": "animal migration.bin",
    "ant": "ant.bin",
    "anvil": "anvil.bin",
    "apple": "apple.bin",
    "arm": "arm.bin",
    "asparagus": "asparagus.bin",
    "axe": "axe.bin",
    "backpack": "backpack.bin",
    "banana": "banana.bin",
    "bandage": "bandage.bin",
    "barn": "barn.bin",
    "baseball bat": "baseball bat.bin",
    "baseball": "baseball.bin",
    "basket": "basket.bin",
    "basketball": "basketball.bin",
    "bat": "bat.bin",
    "bathtub": "bathtub.bin",
    "beach": "beach.bin",
    "bear": "bear.bin",
    "beard": "beard.bin",
    "bed": "bed.bin",
    "bee": "bee.bin",
    "belt": "belt.bin",
    "bench": "bench.bin",
    "bicycle": "bicycle.bin",
    "binoculars": "binoculars.bin",
    "bird": "bird.bin",
    "birthday cake": "birthday cake.bin",
    "blackberry": "blackberry.bin",
    "blueberry": "blueberry.bin",
    "book": "book.bin",
    "boomerang": "boomerang.bin",
    "bottlecap": "bottlecap.bin",
    "bowtie": "bowtie.bin",
    "bracelet": "bracelet.bin",
    "brain": "brain.bin",
    "bread": "bread.bin",
    "bridge": "bridge.bin",
    "broccoli": "broccoli.bin",
    "broom": "broom.bin",
    "bucket": "bucket.bin",
    "bulldozer": "bulldozer.bin",
    "bus": "bus.bin",
    "bush": "bush.bin",
    "butterfly": "butterfly.bin",
    "cactus": "cactus.bin",
    "cake": "cake.bin",
    "calculator": "calculator.bin",
    "calendar": "calendar.bin",
    "camel": "camel.bin",
    "camera": "camera.bin",
    "camouflage": "camouflage.bin",
    "campfire": "campfire.bin",
    "candle": "candle.bin",
    "cannon": "cannon.bin",
    "canoe": "canoe.bin",
    "car": "car.bin",
    "carrot": "carrot.bin",
    "castle": "castle.bin",
    "cat": "cat.bin",
    "ceiling fan": "ceiling fan.bin",
    "cell phone": "cell phone.bin",
    "cello": "cello.bin",
    "chair": "chair.bin",
    "chandelier": "chandelier.bin",
    "church": "church.bin",
    "circle": "circle.bin",
    "clarinet": "clarinet.bin",
    "clock": "clock.bin",
    "cloud": "cloud.bin",
    "coffee cup": "coffee cup.bin",
    "compass": "compass.bin",
    "computer": "computer.bin",
    "cookie": "cookie.bin",
    "cooler": "cooler.bin",
    "couch": "couch.bin",
    "cow": "cow.bin",
    "crab": "crab.bin",
    "crayon": "crayon.bin",
    "crocodile": "crocodile.bin",
    "crown": "crown.bin",
    "cruise ship": "cruise ship.bin",
    "cup": "cup.bin",
    "diamond": "diamond.bin",
    "dishwasher": "dishwasher.bin",
    "diving board": "diving board.bin",
    "dog": "dog.bin",
    "dolphin": "dolphin.bin",
    "donut": "donut.bin",
    "door": "door.bin",
    "dragon": "dragon.bin",
    "dresser": "dresser.bin",
    "drill": "drill.bin",
    "drums": "drums.bin",
    "duck": "duck.bin",
    "dumbbell": "dumbbell.bin",
    "ear": "ear.bin",
    "elbow": "elbow.bin",
    "elephant": "elephant.bin",
    "envelope": "envelope.bin",
    "eraser": "eraser.bin",
    "eye": "eye.bin",
    "eyeglasses": "eyeglasses.bin",
    "face": "face.bin",
    "fan": "fan.bin",
    "feather": "feather.bin",
    "fence": "fence.bin",
    "finger": "finger.bin",
    "fire hydrant": "fire hydrant.bin",
    "fireplace": "fireplace.bin",
    "firetruck": "firetruck.bin",
    "fish": "fish.bin",
    "flamingo": "flamingo.bin",
    "flashlight": "flashlight.bin",
    "flip flops": "flip flops.bin",
    "floor lamp": "floor lamp.bin",
    "flower": "flower.bin",
    "flying saucer": "flying saucer.bin",
    "foot": "foot.bin",
    "fork": "fork.bin",
    "frog": "frog.bin",
    "frying pan": "frying pan.bin",
    "garden hose": "garden hose.bin",
    "garden": "garden.bin",
    "giraffe": "giraffe.bin",
    "goatee": "goatee.bin",
    "golf club": "golf club.bin",
    "grapes": "grapes.bin",
    "grass": "grass.bin",
    "guitar": "guitar.bin",
    "hamburger": "hamburger.bin",
    "hammer": "hammer.bin",
    "hand": "hand.bin",
    "harp": "harp.bin",
    "hat": "hat.bin",
    "headphones": "headphones.bin",
    "hedgehog": "hedgehog.bin",
    "helicopter": "helicopter.bin",
    "helmet": "helmet.bin",
    "hexagon": "hexagon.bin",
    "hockey puck": "hockey puck.bin",
    "hockey stick": "hockey stick.bin",
    "horse": "horse.bin",
    "hospital": "hospital.bin",
    "hot air balloon": "hot air balloon.bin",
    "hot dog": "hot dog.bin",
    "hot tub": "hot tub.bin",
    "hourglass": "hourglass.bin",
    "house plant": "house plant.bin",
    "house": "house.bin",
    "hurricane": "hurricane.bin",
    "ice cream": "ice cream.bin",
    "jacket": "jacket.bin",
    "jail": "jail.bin",
    "kangaroo": "kangaroo.bin",
    "key": "key.bin",
    "keyboard": "keyboard.bin",
    "knee": "knee.bin",
    "knife": "knife.bin",
    "ladder": "ladder.bin",
    "lantern": "lantern.bin",
    "laptop": "laptop.bin",
    "leaf": "leaf.bin",
    "leg": "leg.bin",
    "light bulb": "light bulb.bin",
    "lighter": "lighter.bin",
    "lighthouse": "lighthouse.bin",
    "lightning": "lightning.bin",
    "line": "line.bin",
    "lion": "lion.bin",
    "lipstick": "lipstick.bin",
    "lobster": "lobster.bin",
    "lollipop": "lollipop.bin",
    "mailbox": "mailbox.bin",
    "map": "map.bin",
    "marker": "marker.bin",
    "matches": "matches.bin",
    "megaphone": "megaphone.bin",
    "mermaid": "mermaid.bin",
    "microphone": "microphone.bin",
    "microwave": "microwave.bin",
    "monkey": "monkey.bin",
    "moon": "moon.bin",
    "mosquito": "mosquito.bin",
    "motorbike": "motorbike.bin",
    "mountain": "mountain.bin",
    "mouse": "mouse.bin",
    "moustache": "moustache.bin",
    "mouth": "mouth.bin",
    "mug": "mug.bin",
    "mushroom": "mushroom.bin",
    "nail": "nail.bin",
    "necklace": "necklace.bin",
    "nose": "nose.bin",
    "ocean": "ocean.bin",
    "octagon": "octagon.bin",
    "octopus": "octopus.bin",
    "onion": "onion.bin",
    "oven": "oven.bin",
    "owl": "owl.bin",
    "paint can": "paint can.bin",
    "paintbrush": "paintbrush.bin",
    "palm tree": "palm tree.bin",
    "panda": "panda.bin",
    "pants": "pants.bin",
    "paper clip": "paper clip.bin",
    "parachute": "parachute.bin",
    "parrot": "parrot.bin",
    "passport": "passport.bin",
    "peanut": "peanut.bin",
    "pear": "pear.bin",
    "peas": "peas.bin",
    "pencil": "pencil.bin",
    "penguin": "penguin.bin",
    "piano": "piano.bin",
    "pickup truck": "pickup truck.bin",
    "picture frame": "picture frame.bin",
    "pig": "pig.bin",
    "pillow": "pillow.bin",
    "pineapple": "pineapple.bin",
    "pizza": "pizza.bin",
    "pliers": "pliers.bin",
    "police car": "police car.bin",
    "pond": "pond.bin",
    "pool": "pool.bin",
    "popsicle": "popsicle.bin",
    "postcard": "postcard.bin",
    "potato": "potato.bin",
    "power outlet": "power outlet.bin",
    "purse": "purse.bin",
    "rabbit": "rabbit.bin",
    "raccoon": "raccoon.bin",
    "radio": "radio.bin",
    "rain": "rain.bin",
    "rainbow": "rainbow.bin",
    "rake": "rake.bin",
    "remote control": "remote control.bin",
    "rhinoceros": "rhinoceros.bin",
    "rifle": "rifle.bin",
    "river": "river.bin",
    "roller coaster": "roller coaster.bin",
    "rollerskates": "rollerskates.bin",
    "sailboat": "sailboat.bin",
    "sandwich": "sandwich.bin",
    "saw": "saw.bin",
    "saxophone": "saxophone.bin",
    "school bus": "school bus.bin",
    "scissors": "scissors.bin",
    "scorpion": "scorpion.bin",
    "screwdriver": "screwdriver.bin",
    "sea turtle": "sea turtle.bin",
    "see saw": "see saw.bin",
    "shark": "shark.bin",
    "sheep": "sheep.bin",
    "shoe": "shoe.bin",
    "shorts": "shorts.bin",
    "shovel": "shovel.bin",
    "sink": "sink.bin",
    "skateboard": "skateboard.bin",
    "skull": "skull.bin",
    "skyscraper": "skyscraper.bin",
    "sleeping bag": "sleeping bag.bin",
    "smiley face": "smiley face.bin",
    "snail": "snail.bin",
    "snake": "snake.bin",
    "snorkel": "snorkel.bin",
    "snowflake": "snowflake.bin",
    "snowman": "snowman.bin",
    "soccer ball": "soccer ball.bin",
    "sock": "sock.bin",
    "speedboat": "speedboat.bin",
    "spider": "spider.bin",
    "spoon": "spoon.bin",
    "spreadsheet": "spreadsheet.bin",
    "square": "square.bin",
    "squiggle": "squiggle.bin",
    "squirrel": "squirrel.bin",
    "stairs": "stairs.bin",
    "star": "star.bin",
    "steak": "steak.bin",
    "stereo": "stereo.bin",
    "stethoscope": "stethoscope.bin",
    "stitches": "stitches.bin",
    "stop sign": "stop sign.bin",
    "stove": "stove.bin",
    "strawberry": "strawberry.bin",
    "streetlight": "streetlight.bin",
    "string bean": "string bean.bin",
    "submarine": "submarine.bin",
    "suitcase": "suitcase.bin",
    "sun": "sun.bin",
    "swan": "swan.bin",
    "sweater": "sweater.bin",
    "swing set": "swing set.bin",
    "sword": "sword.bin",
    "syringe": "syringe.bin",
    "t-shirt": "t-shirt.bin",
    "table": "table.bin",
    "teapot": "teapot.bin",
    "teddy-bear": "teddy-bear.bin",
    "telephone": "telephone.bin",
    "television": "television.bin",
    "tennis racquet": "tennis racquet.bin",
    "tent": "tent.bin",
    "The Eiffel Tower": "The Eiffel Tower.bin",
    "The Great Wall of China": "The Great Wall of China.bin",
    "The Mona Lisa": "The Mona Lisa.bin",
    "tiger": "tiger.bin",
    "toaster": "toaster.bin",
    "toe": "toe.bin",
    "toilet": "toilet.bin",
    "tooth": "tooth.bin",
    "toothbrush": "toothbrush.bin",
    "toothpaste": "toothpaste.bin",
    "tornado": "tornado.bin",
    "tractor": "tractor.bin",
    "traffic light": "traffic light.bin",
    "train": "train.bin",
    "tree": "tree.bin",
    "triangle": "triangle.bin",
    "trombone": "trombone.bin",
    "truck": "truck.bin",
    "trumpet": "trumpet.bin",
    "umbrella": "umbrella.bin",
    "underwear": "underwear.bin",
    "van": "van.bin",
    "vase": "vase.bin",
    "violin": "violin.bin",
    "washing machine": "washing machine.bin",
    "watermelon": "watermelon.bin",
    "waterslide": "waterslide.bin",
    "whale": "whale.bin",
    "wheel": "wheel.bin",
    "windmill": "windmill.bin",
    "wine bottle": "wine bottle.bin",
    "wine glass": "wine glass.bin",
    "wristwatch": "wristwatch.bin",
    "yoga": "yoga.bin",
    "zebra": "zebra.bin",
    "zigzag": "zigzag.bin",
    }